channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=23.2.1
- pip:
  - mlflow==2.17.0
  - cloudpickle==3.1.0
  - numpy==2.1.2
  - pandas==2.2.3
  - psutil==6.0.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
